---
title: "a2_task2_leonardo_feitosa"
author: "Leonardo Feitosa"
date: "31/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(naniar)
library(stargazer)
library(broom)
library(GGally)
```


## Read in the data

```{r}
palmetto <- read_csv(here("data", "palmetto.csv"), 
                     col_types = cols(.default = 'c')) %>% 
  mutate(across(.cols = height:green_lvs, as.numeric)) %>% 
  mutate(species_full = case_when(
    species %in% 1 ~ "Serenoa",
    species %in% 2 ~ "Sabal"
  )) %>% 
  relocate(species_full, .after = species)

# Palmetto subset
palmetto_sub <- palmetto %>% 
  select(species_full, species, height, length, width, green_lvs) %>% 
  drop_na()

# Checking which is which
levels(palmetto$species_full)
```



## Data Viz

```{r}
# Exploratory plots

ggpairs(palmetto_sub, aes(color = species_full))

# First plot
ggplot(palmetto_sub, aes(x = species_full, y = height)) +
  geom_jitter(color = "goldenrod4",
              alpha = 0.3,
              width = 0.35) +
  geom_boxplot(aes(fill = species_full),
               show.legend = F,
               alpha = 0.9) +
  scale_fill_brewer(palette = "Set1") +
  labs(x = "Species",
       y = "Height") +
  theme_classic() +
  theme(axis.title = element_text(size = 12, color = "black", face = "bold"),
        axis.text = element_text(size = 10, color = "gray18"),
        axis.text.x = element_text(face = "italic"))

# Second plot
ggplot(palmetto_sub, aes(x = height, y = width)) +
  geom_point(aes(color = species_full),
             show.legend = F) +
  labs(x = "Height",
       y = "Width") +
  theme_bw() +
  theme(axis.title = element_text(size = 12, color = "black", face = "bold"),
        panel.grid = element_blank())

# Third plot
ggplot(palmetto_sub, aes(x = height, y = green_lvs)) +
  geom_point(aes(color = species_full),
             show.legend = F) +
  labs(x = "Height",
       y = "Length") +
  theme_bw() +
  theme(axis.title = element_text(size = 12, color = "black", face = "bold"),
        axis.text = element_text(size = 10, color = "gray18"),
        panel.grid = element_blank())
```





## Binary logistic regression

```{r}
palmetto_blr <- glm(species_full ~ length + height + width + green_lvs, data = palmetto_sub, family = "binomial")

palmetto_blr

# Model outputs
summary(palmetto_blr)

palmetto_blr_tidy <- broom::tidy(palmetto_blr)
```

```{r, results = 'asis', echo = FALSE}
# Finalized table
stargazer(palmetto_blr, type = "html")
```




```{r}
# Fitted model
palmetto_blr_fitted <- palmetto_blr %>% 
  broom::augment(type.predict = "response")


# Data viz for fitted model
ggplot(data = palmetto_blr_fitted, aes(x = length, y = .fitted)) +
  geom_point(aes(color = species)) +
  geom_smooth(aes(color = species), se = FALSE) +
  theme_bw()
```

```{r}
palmetto_outcome <- palmetto_blr_fitted %>% 
  predict(data.frame = (species))
  mutate_if(.fitted >= 0.5)
```









