---
title: "a2_task3_leonardo_feitosa"
author: "Leonardo Feitosa"
date: "01/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytuesdayR)
library(naniar)
library(ggalluvial)
library(magick)
library(here)
library(showtext)
```

## Read in the data
```{r}
tuesdata <- tidytuesdayR::tt_load(2021, week = 5)

plastics <- tuesdata$plastics
```

## Data wrangling

```{r}
plastics_tidy <- plastics %>% 
  pivot_longer(cols = empty:pvc,
               names_to = "recycling_code",
               values_to = "abundance") %>% 
  mutate(year = as.character(year)) %>% 
  drop_na()

plastics_count <- plastics_tidy %>%
  mutate(country = fct_reorder(country, abundance)) %>% 
  count(country, recycling_code, year, wt = abundance) %>% 
  slice_max(country, n = 20) %>% 
  slice(-(1:2)) %>%
  filter(recycling_code %in% c("o",
                               "pc",
                               "pet",
                               "pp")) %>% 
  mutate(country = case_when(
    country %in% c("United States of America") ~ "USA",
    country %in% c("Vietnam") ~ "Vietnam"
  )) %>% 
  as.data.frame()
```

## Using the function `fct_recode()` from `forcats`

```{r}
plastics_fct <- plastics_tidy %>% 
  fct_recode(country, USA = "United States of America")
```

# New ggplot theme

```{r}
# Add font from google
font_add_google("Roboto")


theme_slate <- function() {
  theme(
    panel.border = element_rect(color = "cyan4", fill = NA, linetype = "solid"),
    panel.background = element_rect(fill = "white"),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.x = element_line(colour = "darkslateblue",
                                      linetype = 2,
                                      size = 1),
    panel.grid.major.y = element_line(colour = "darkslateblue",
                                      linetype = 2,
                                      size = 1),
    panel.grid.minor.y = element_blank(),
    plot.title = element_text(family = "Roboto", face = "bold", size = 15),
    axis.text = element_text(colour = "black", face = "bold"),
    axis.title = element_text(colour = "black"),
    axis.ticks = element_blank(),
    legend.position = "top"
  )
}
```


## Reading and editing an image with `magick`

```{r}
coke <- image_read(here("data", "coke.png"))

print(coke)

image_trim(coke)
image_resize(coke, "600")
```


## Data viz

```{r, warning = FALSE}
plastics_america <- plastics_tidy %>% 
  filter(country %in% c("Brazil",
                        "Argentina",
                        "Peru",
                        "Colombia",
                        "Chile",
                        "Ecuador",
                        "Mexico",
                        "United States of America",
                        "Canada",
                        "El Salvador",
                        "Honduras")) %>% 
  select(country, year, recycling_code, abundance, parent_company) %>% 
  mutate(america = case_when(
    country %in% c("Brazil",
                        "Argentina",
                        "Peru",
                        "Colombia",
                        "Chile",
                        "Ecuador") ~ "South",
    country %in% c("United States of America",
                   "Canada") ~ "North",
    country %in% c("Mexico",
                   "Honduras",
                   "El Salvador") ~ "Central"
  )) %>% 
  filter(recycling_code %in% c("o",
                               "pet",
                               "pp")) %>% 
  mutate(recycling_code = case_when(
    recycling_code %in% c("o") ~ "Other",
    recycling_code %in% c("pet") ~ "PET",
    recycling_code %in% c("pp") ~ "PP"
  )) %>% 
  filter(parent_company %in% c("The Coca Cola Company",
                               "PepsiCo",
                               "Unbranded"))

plastics_america_count <- plastics_america %>% 
  count(country, recycling_code, parent_company, year, america, wt = abundance) %>% 
  as.data.frame()
```


## Working on the `ggalluvial` package

```{r}
is_alluvia_form(plastics_america_count, axes = 1:3, silent = T)


ggplot(data = plastics_america_count, aes(y = n,
                                          axis1 = country,
                                          axis2 = recycling_code,
                                          axis3 = america)) +
  geom_alluvium(aes(fill = year), 
                width = 1/12,
                reverse = FALSE) +
  geom_stratum(width = 1/12,
               fill = "white",
               color = "goldenrod4") +
  geom_label(stat = "stratum", 
             aes(label = after_stat(stratum))) +
  geom_flow() +
  scale_x_discrete(limits = c("country", 
                              "recycling_code"), 
                   expand = c(.05, .02)) +
  labs(y = "Counts",
       title = "Title",
       fill = "Year") +
  theme_slate()

ggsave(here("fig", "alluvial.png"), width = 12, height = 10)

alluvial <- image_read(here("fig", "alluvial.png"))

new_plot <- alluvial %>% 
  image_composite(bottle, offset = "+3900+2500")

image_scale(new_plot, "600")

ggsave(here("fig", "alluvial_new.png"), width = 12, height = 10)


# Lodes

plas_ame_ct_lode <- to_lodes_form(plastics_america_count,
                                  axes = 1:2,
                                  id = "continent")


head(plas_ame_ct_lode, n = 10)

is_lodes_form(plas_ame_ct_lode, key = , value = stratum, id = continent, silent = TRUE)

```




## gganimate()

```{r}
p <- ggplot(data = plastics_filter, aes(x = country, y = sum)) +
  geom_point() +
  transition_states(year,
                    transition_length = 2,
                    state_length = 1)
  
p
anim <- p +
  transition_states(year,
                    transition_length = 2,
                    state_length = 1) +
  theme_bw()

anim
```
























